services:
  postgres:
    image: postgres:16-alpine
    container_name: food_order_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: food_order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
